apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barista
  namespace: rz8zp-argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rz8zp-prod-coffeeshop
  project: coffee-shop
  source:
    path: ./coffee-shop-kustomize/barista/overlays/production
    repoURL: http://homework-gitea.gpte-hw-cicd.svc:3000/earvonen-redhat.com-rz8zp/coffee-shop-final-lab.git
    targetRevision: HEAD
