
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop-pipeline
  namespace: openshift-gitops
spec:
  destination:
    namespace: coffee-shop-pipeline
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./coffee-shop-projects
    repoURL: https://github.com/earvonen/coffee-shop-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: false
