apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop-pipeline
  namespace: rz8zp-argocd
spec:
  destination:
    namespace: rz8zp-pipeline
    server: https://kubernetes.default.svc
  project: coffee-shop
  source:
    path: ./coffee-shop-pipeline
    repoURL: http://homework-gitea.gpte-hw-cicd.svc:3000/earvonen-redhat.com-rz8zp/coffee-shop-final-lab.git
    targetRevision: HEAD
